services:
  postgres:
    image: postgres:17
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_pwd
      POSTGRES_DB: mts_teams
    ports:
      - "5633:5432"
